### ISSUE TITLE
Implement dictionary ops -- somehow

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#10]
The only value types here are
- Int
- SymT - also Int
- Packed data

I don't even know if we need Ints.  Basically we want to be able to write passes like `inline` that keep an environment of tree values (pointers into existing buffers) as they walk down the tree.  If we just assume `void*` that covers all three of the above: a single word.

**Comment by rrnewton** [comment]
Changing the title because I think it's quite unclear how we want dictionaries to work.  For immutable/shared dictionaries maybe we just want to get the language to the point where we can implement them directly.  It's very unclear how we could have a good mem mgmt strategy with them implemented as primops.  We'd need a good C library for persistant hashmaps of some kind, that would integrate with... what, conservative GC?

**Comment by rrnewton** [comment]
But for a Haskell backend it's fine that these be primops.  We can have a family of primops that map directly onto standard Haskell functions in that backend.

**Comment by vollmerm** [comment]
I want to revive this issue, but most of this discussion is outdated, so I'll make a new issue.
