### ISSUE TITLE
Support a fully polymorphic frontend

### ISSUE THREAD

**Issue by ckoparkar** [iu-parfunc/gibbon#103]
A lot of the pieces for the polymorphic front-end are in place. This issue tracks the remaining work:

- [x] Keep rigid type variables separate from meta/unification variables in the typechecker

... so that programs like this bogus `id` do not typecheck:

```Haskell
id :: a -> a
id x = 10
```

- [x] Lambda lifting

In addition to being monomorphic, `L1` is also first order, so we can't have any lambdas in the program. Floating out the lambda definitions is straightforward. Fixing all the parts that accept lambdas requires a little more work. Consider this monomorphic `fmap`: 

```Haskell
fmap_1 :: ((Int -> Int), Maybe Bool) -> Maybe Int
fmap_1 tup = let f = tup !! 0
                 thing = tup !! 1
              ...
```

To lift all lambdas, a lot of parts in the program will have to change. In `fmap_1`, the argument doesn't even have to a tuple anymore. In some cases, it might still be a tuple but we'll have to fix all the `tup !! ix` instances.

- [ ] Support projections in Gibbon's Haskell subset

`!!`, `nth`, `#`, or something else ?

- [ ] Basic `import` capabilities

- [x] Anonymous lambdas (0bdd68576ce98608bf9195dc549e267fb395321f)

- [x] Curried functions...

`Gibbon.L0.Specialize` accomplishes this. We just have to use that in the main pipeline.

See the [haskell-frontend](https://github.com/iu-parfunc/gibbon/tree/haskell-frontend) branch for the latest commits. [edit: merged into `master`]

**Comment by ckoparkar** [comment]
Gibbon can now typecheck and specialize this (somewhat contrived) higher order polymorphic [program](https://github.com/iu-parfunc/gibbon/blob/haskell-frontend/gibbon-compiler/examples/hs/Spec2.hs).

TODO: curried functions

**Comment by rrnewton** [comment]
@ckoparkar - what's the plan on "basic import capabilities"?  Is it to treat as `#include` and squish the program into one file for whole-program compilation?

We could do that in Gibbon, but then Gibbon has to replicate GHC's path resolution and import-chasing code.  Maybe that's fine.  Also, one could potentially do it as a preprocessor which really would just produce one big `.hs` file.  (This would be like the opposite of [fragnix](http://haskellexists.blogspot.com/2015/03/a-very-first-step-towards-fragment.html)!)

@RyanGlScott could probably comment on the best (modern) way to do that... is it with the GHC API?  Via TemplateHaskell?  Something else?

**Comment by ckoparkar** [comment]
> (2) eta expand all other curried-function apps: f x => \ y -> \z -> f x y z

@rrnewton 13ae37201b33aa626e6a7fe7c6b722fc162f50f8 implements this idea. `master` now has support for anonymous lambdas and curried functions. TODOs: `import`s and closure conversion (right now, we just report an error if a lambda uses anything other than it's arguments).

**Comment by ckoparkar** [comment]
The L0 front-end is sufficiently expressive for now.
