### ISSUE TITLE
Add Haskell backend or adjust L1 pretty printing

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#106]
The idea here is to provide an additional point of comparison for the performance of these programs (e.g. after fusion).  Also, this provides a good additional form of testing.

One idea that came up today is that rather than a proper "backend", the L1 pretty printing could be tweaked to be completely valid Haskell in the first place.

 * [x] Also, we'll want the verbose output (`-v4`) to have the option of dumping to a series of files (like GHC `-ddump`) instead of to the screen.

**Comment by ckoparkar** [comment]
The Haskell pretty printer is in an OK shape on `master`. E.g.

    $ stack exec gibbon -- -r -v1 --ddump-hs --ddump-to-file examples/render_tree.hs

This generates `examples/test_sumup_seteven.gibbon_hs.hs` which should compile with GHC. We still need to flesh out some Gibbon primitives -- `time`, `iterate`, `size-param`, `rand`.

@laithsakka @vollmerm

**Comment by ckoparkar** [comment]
This is done, modulo the timing primitives. I'm closing this as there is a separate issue to track that.
