### ISSUE TITLE
Support timeIt in Haskell input and output.

### ISSUE THREAD

**Issue by laithsakka** [iu-parfunc/gibbon#123]
Currently, Gibbon timeIt function is translated to Id function in Haskell output.

Whenever an evaluation is needed to be done manual changes are made to
the output Haskell to allow that, which is time-consuming. 
We should add a flag that when enabled automatically generates such changes in the
output Haskell code.

Furthermore, there is not a timeIt construct in the current input Haskell, having such a thing 
also is needed.

**Comment by laithsakka** [comment]
If anybody is working on this I suggest the following for timing.

main =
 do
  performMajorGC
  let fltAppE732 :: Document = buildDoc1
  t1 <-fltAppE732  `deepseq` getCurrentTime
  t2 <-  (gibbon_main2 fltAppE732) `deepseq` getCurrentTime
  print $ diffUTCTime t2 t1

**Comment by ckoparkar** [comment]
@laithsakka So far we've been using `median of 9 trials` to measure things, where a single trial is pretty much what your snippet does. And we can continue doing that for this paper too. Or, we could use [`criterion`](http://www.serpentine.com/criterion/) and have gibbon generate code for that.

I'm having trouble remembering all the details of why we didn't use it for the last paper. We wanted to benchmark arbitrary exe's, so we couldn't use the `criterion` library. And I think we did not have enough time to get our C files to work with  [`criterion-interactive`](https://github.com/rrnewton/criterion-external).

@rrnewton @milindkulkarni do you have an opinion on criterion vs not-criterion ?

**Comment by vollmerm** [comment]
Do we want to support `timeIt` in arbitrary places in the program, like in normal Gibbon, or do we only need to time the main expression? The latter would be easier, since doing the timing would be an `IO` action.

**Comment by ckoparkar** [comment]
@vollmerm For the Haskell backend I was thinking of allowing a `timeit` only in the main expression. That's how most benchmarks use it anyways. We can't cheat here and embed an `IO` in arbitrary places like we do in Gibbon :D

**Comment by ckoparkar** [comment]
This is related to Gibbon's Haskell backed. Since that's not being used anymore I'll go ahead and close this for now. We can reopen later if required.
