### ISSUE TITLE
Float letregions inward

### ISSUE THREAD

**Issue by ckoparkar** [iu-parfunc/gibbon#133]
The current [location inference](https://github.com/iu-parfunc/gibbon/blob/231bd883a8399122c01c7e0726c16317d09accd1/gibbon-compiler/src/Gibbon/Passes/InferLocations.hs) algorithm always puts all `letregion`s at the top of the function body. But if a function has a conditional or a case expression right after such that the region isn't always used, it would be good to float the `letregion` (and any locations within the region) closer to the point where they're needed to avoid this unnecessary region creation and collection.

For example, we'd like to turn

```
f :: List Int @ r1 -> List Int @ r2
f xs =
  letregion r in
    case xs of
      Nil -> ... allocate to r ... allocate to r2 ...
      Cons y ys -> allocate to r2
```

into

```
f :: List Int @ r1 -> List Int @ r2
f xs =
    case xs of
      Nil -> letregion r in ... allocate to r ... allocate to r2 ...
      Cons y ys -> allocate to r2
```

**Comment by vid-999** [comment]
Implemented the compiler pass in this file:
https://github.com/iu-parfunc/gibbon/blob/a48a09eb19c13c47ce47d93b525fc9f78c14dd8c/gibbon-compiler/src/Gibbon/Passes/RegionsInwards.hs#L1
