### ISSUE TITLE
BST insertion fails to add some nodes

### ISSUE THREAD

**Issue by jazullo** [iu-parfunc/gibbon#194]
(Tested on commit `2fc0301`)
Consider the following Gibbon code: 
```
data Tree = E | T Int Tree Tree

empty :: Tree -> Bool
empty t = case t of
  E -> True
  T x y z -> False

insert :: Tree -> Int -> Tree
insert t x = case t of
  E -> T x E E
  T v t1 t2 ->
    if v == x then t
    else if v < x then T v t1 (insert t2 x)
    else T v (insert t1 x) t2

gibbon_main = 
  let
    _ = printPacked (insert (insert E 1) 2)
  in ()
```
With the integers `1` and `2` on the final line, the representation is printed as so: 
`(T 1 ->i (E )(E ))'#()`
which is missing the `2` node. 

If we swap the `2` for a `0`, so the additional node is added to the left rather than the right, the representation is as so: 
`(T 1(T 0(E )(E )) ->i (E ))'#()`
which appears to be correct.

**Comment by vid-999** [comment]
@jazullo This doesn't seem to be an issue anymore on the latest master branch.
