### ISSUE TITLE
Cleanup, debugging, and robustness tasks for compiler prototype

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#20]
That pre-PLDI hacking sprint left quite a bit of technical debt behind.  Here is the plan for getting things on solid footing:

 * [ ] Stop using a pattern synonym hack to encode CursorsTy's as PackedTy.  Make it its own type in L1.  The `WriteInt` pattern synonyms are much less of a problem.  They can probably stay.
 * [x] Add an interpreter and run it after (almost) every pass.
 * [x] Run the type checker after (almost) every pass and debug any remaining problems.
 * [ ] Add linear/session types to the type system and type checker (#41)

**Comment by ckoparkar** [comment]
*** Tests

(1) Audit all the existing tests and remove obsoletes. Also, we should add some new ones that exercise various parts of the compiler to try and catch all the corner cases.

(2) The current framework stops running the testsuite as soon as it encounters a failure. Instead, it should just record the failed test# and continue running the others, and then report all the failures at the end.


*** Benchmarks

Setup something like `nofib`, which records various details (time, space, allocs etc.) for certain tests, and ensures that they're within a (expected ± delta) bound. We may not want to run this on _every_ commit, but running this periodically or before merging certain branches would be nice. (This should help avoid some the issues we had with benchmarking in the last submission)

*** Revamp debugging

Debugging Gibbon errors is way to difficult sometimes.

The process basically is:
(1) Turn up the verbosity level to the highest value, and dump the output of all the compiler passes.
(2) Manually inspect the output of every pass from `InferLocations` to `Cursorize` (that roughly 10 passes!) to try and spot the error.

We should do something to make this easier. The first step is to probably run the interpreter after _every_ pass (we only run it on L1 programs atm). Also, we could add some additional passes that validate the AST after certain passes. This could help us track down the errors faster. 

...

**Comment by ckoparkar** [comment]
Tracked in #89.
