### ISSUE TITLE
Running the Test Suite

### ISSUE THREAD

**Issue by jazullo** [iu-parfunc/gibbon#210]
[Trying to run the test suite nets me this error. ](https://gist.github.com/jazullo/1c170baf2639b3ebc8f85750b00799d5)
I am `cd`ing into `gibbon-compiler` and then running the script. I'm not sure if there's something in my approach I'm missing. I tried replacing v1-install with v2-install but then it cannot find the project. Any help would be appreciated, thanks.

**Comment by vid-999** [comment]
I added the command to the google doc notes today, the tests can be run by following the steps below. 
 
1.) from the `gibbon` directory    `source set_env.sh`
2.) from the` gibbon-compiler` directory ` cabal v2-exec -w ghc test-gibbon-examples -- -v2`

ghc == ghc binary

**Comment by jazullo** [comment]
I get `fatal error: gc.h: No such file or directory` on every test case
```
Executing TestRunner...

Generating answers...Done.
Running tests...

AnonLambdas.hs...FAILED

Pointer:
  /home/joey/gibbon/gibbon-compiler/examples/build_tmp/AnonLambdas_ptr.c:25:10: fatal error: gc.h: No such file or directory
       25 | #include <gc.h>
          |          ^~~~~~
    compilation terminated.
    gibbon: C compiler failed!  Code: 1
    CallStack (from HasCallStack):
      error, called at src/Gibbon/Compiler.hs:364:22 in gibbon-0.2-inplace:Gibbon.Compiler
```

**Comment by vid-999** [comment]
That's weird I don't get that error on the master branch. 
Anyways that's for the pointer mode. If you are not working with the pointer mode specifically you can probably ignore that.

**Comment by jazullo** [comment]
Here's the error I get when running the `cabal v2-exec -w ghc-9.0.1 test-gibbon-examples -- -v2` command. 
```
joey@DESKTOP-1AM9RQH:~/gibbon/gibbon-compiler$ cabal v2-exec -w ghc-9.0.1 test-gibbon-examples -- -v2
Executing TestRunner...

Generating answers...test-gibbon-examples: make: createProcess: runInteractiveProcess: chdir: does not exist (No such file or directory)
```

**Comment by vid-999** [comment]
from the `gibbon` directory source `set_env.sh`

**Comment by jazullo** [comment]
Thanks - this gets the tests running, though the [vast majority of them fail due to the previous error with `gc.h` not being found](https://gist.github.com/jazullo/98d4373c8729b8f3a4147f4dce06aeec). I'm not sure how to fix this issue with that not being linked.

**Comment by ckoparkar** [comment]
@jazullo Do you [Boehm GC](https://packages.ubuntu.com/focal/amd64/libgc-dev) installed on your machine? 

Usually, the [shell.nix](https://github.com/iu-parfunc/gibbon/blob/a48a09eb19c13c47ce47d93b525fc9f78c14dd8c/shell.nix) file is a good reference on what dependencies are required, or, the [CI script](https://github.com/iu-parfunc/gibbon/blob/a48a09eb19c13c47ce47d93b525fc9f78c14dd8c/.github/workflows/test-gibbon.yml) which should also tell you how it runs the tests.

**Comment by ckoparkar** [comment]
(I'll check the `run_all_tests.sh` script and the README and fix out-of-date things.)

**Comment by jazullo** [comment]
Thank you - installing `libgc-dev` fixes the errors with `gc.h`. However, now I'm receiving errors `#include <cilk/cilk.h>` and I'm not sure which version of cilk to install, it's not obvious to me from the scripts.

**Comment by vid-999** [comment]
Gcc7 used to come with cilk on Ubuntu 18.04. With newer Ubuntu versions gcc doesn't have cilk as an integrated library anymore.

To get around that temporarily I use clang by modifying the compiler to clang in gibbon and installing open cilk.

**Comment by jazullo** [comment]
I have opencilk installed now. It looks like the Gibbon compiler itself lets you choose a C compiler with the `--cc` option, we should probably extend this option to the test runner or have the ability to provide arguments to Gibbon in general. 

For the time being I suppose modifying the compiler would work. I would be interested to know what your changes are. I've tried modifying it myself and tried some things but wasn't able to get it to work.

**Comment by vid-999** [comment]
Hi Joseph, 

Here are the changes that I make: 

1.) In Common.hs change the cc compiler to opencilk clang
2.) In Compiler.hs change the fcilkplus flag to fopencilk 

Here is a branch where you can see the changes that I made: 
https://github.com/iu-parfunc/gibbon/commit/3b6afcbaf8882d829efadff9469001d42f1051d3

Once you make these changes recompile gibbon and run the test suite again. 

Though, its seems like with the latest llvm version there are errors in the C code that gibbon generates. These need to be corrected if we need to support llvm as a compiler option.

**Comment by jazullo** [comment]
Thank you, 

With these changes far fewer things fail, however I'm still not replicating the test results you posted earlier. My test summary is the following: 
```
144 expected passes
0 unexpected passes
28 expected failures
12 unexpected failures
31 skipped
```
https://gist.github.com/jazullo/ad91fe51ea38f037f512e14eb59e49c3

A concerning number of test cases seem to be ending in segfaults. Let me know if there's some way I can fix this or if this is a good enough test suite for now. 

I wrote some scripts to help automate regexing in and out the c compiler, I'm not sure this is the best approach but I can share these if you want.

**Comment by vid-999** [comment]
Hi Joeph the previous test results I had were with gcc not with opencilk. 

I re-ran the results with latest opencilk and get the same results as you do. 

```
Gibbon testsuite summary:  (2023-05-28 17:37:44.522672456 EDT)
--------------------------------------------------------------------------------
Time taken: 125s

144 expected passes
0 unexpected passes
28 expected failures
12 unexpected failures
31 skipped

Skipped: 
--------------------------------------------------------------------------------
void_type.hs, void_type.gib, test_sumup_seteven.gib, test_circsim.hs, test_168.hs, test27b_subst.gib, test26_treewalk.gib, test25f_countnodes.gib, test24_defs.gib, test18_badconstraint.gib, test17_forfold.gib, test16_forlist.gib, test15c_printsym.gib, test15b_symappend.gib, test14b_tup.gib, test12_skip.gib, test06c_nested.gib, render_tree_two_passes.hs, render_tree_four_passes.hs, render_tree_five_passes.hs, render_tree.hs, pp_projs.gib, bench_compose2.gib, bench_compose1.gib, Test187.hs, T64_2.gib, Sort.hs, NestedTuples.hs, LC.hs, CurriedFns.hs, C1.hs
```
Regarding the segfaults, like i said previously, the C code that gibbon generates isn't compatible with the latest LLVM version in that the `-O3` optimization that the compiler is doing causes a bug in the code which is causing the segfaults. 

If I change the optimization level to `-O0` in Common.hs then the suite runs as expected. 

```
Gibbon testsuite summary:  (2023-05-28 17:47:21.686418293 EDT)
--------------------------------------------------------------------------------
Time taken: 39s

145 expected passes
0 unexpected passes
28 expected failures
0 unexpected failures
31 skipped

Skipped: 
--------------------------------------------------------------------------------
void_type.hs, void_type.gib, test_sumup_seteven.gib, test_circsim.hs, test_168.hs, test27b_subst.gib, test26_treewalk.gib, test25f_countnodes.gib, test24_defs.gib, test18_badconstraint.gib, test17_forfold.gib, test16_forlist.gib, test15c_printsym.gib, test15b_symappend.gib, test14b_tup.gib, test12_skip.gib, test06c_nested.gib, render_tree_two_passes.hs, render_tree_four_passes.hs, render_tree_five_passes.hs, render_tree.hs, pp_projs.gib, bench_compose2.gib, bench_compose1.gib, Test187.hs, T64_2.gib, Sort.hs, NestedTuples.hs, LC.hs, CurriedFns.hs, C1.hs
```

**Comment by jazullo** [comment]
Adding `-O0` I get the same results. 
```
145 expected passes
0 unexpected passes
28 expected failures
0 unexpected failures
31 skipped
```
Thank you very much for your help, I think we can consider this done.

**Comment by ulysses4ever** [comment]
Given that the topic starter seemed to be satisfied, this is about the time we close it.
