### ISSUE TITLE
Use actual symbols, not strings for variables in the compiler's ASTs

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#23]
This is a no-brainer for any compiler.  But we started off with expediency as paramount here.

Of the ~3 libraries I'd tested in the past, it looks like [symbol](https://www.stackage.org/lts-7.13/package/symbol-0.2.4) is the only one in stackage.

**Comment by ckoparkar** [comment]
We already implemented this, but forgot to close this issue after.
