### ISSUE TITLE
Make linear+session types real

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#41]
This will be a major step up in assurance for the compiler internals.  The core cursorizing transform is really so complicated and error prone that it warrants it.

I won't describe the technique here.  [Read the paper for more details.](http://www.cs.indiana.edu/~rrnewton/papers/gibbon_working_draft.pdf).

P.S. Note that if this were implemented in a type-indexed, Accelerate style, we could consider doing it at the host type-system level, and thus verifying that our compiler passes correctly handle cursors for *all* inputs.  That's a lot of work, though.  It would probably happen in an inverted version of the technique described in the ghostbuster paper.  You would need to go to an indexed representation, do the verified transform, and then drop back down.  Either that or refactor the whole compiler.  But we have generally felt that that provides too high a cost/benefit ratio.  Perhaps there are lighter weight (static) verification techniques...  In the meantime, the more dynamic testing approach in this issue should do quite well.

**Comment by vollmerm** [comment]
We changed direction and this is no longer going to be implemented.

**Comment by rrnewton** [comment]
Yeah, I agree that this is obsolete.  Thanks for triaging.  In the new system, @vollmerm's L2 typechecker already ensures that locations are already written once.  It would probably be overkill to try to ensure that cursors are used linearly once we get to L3.

The place linearity may eventually come back is in the front end language (L0).  If we use the Linear Haskell design in the front end, GHC will actually be checking the linearity.  This would be in service of fusion (@laithsakka), which takes multiple distinct forms:

 * On out of place tree transforms `A->B->C`, if the tree traversals are linearly typed, that *guarantees* that fusion is safe, shifting burden from the program analysis to the type system.
 * On an out-of-place-transform `A->B` or `A->A`, the *final deforestation* would be to convert to an in-place traversal via mutation of the input tree.  Linearity of the source program guarantees that the input may be destroyed.
 * Implementing in-place traversal can use various representations in the compiler, it can look like executing new data-constructors, but just-freed old memory (a la clean), or it can use explicit mutation on the cells that make up the tree.
 * Re: explicit mutation, Once we have such linear types, they could be exposed in the front-end to expose mutable data structures and allow writing of in-place traversals directly.
