### ISSUE TITLE
Implement list primitives

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#45]
This will be substantial work, but is still a good idea for all the originally cited reasons.

Here are some notes on it:

- `error "FINISHLISTS"` is inserted in many (but not all) necessary places in the codebase.  Grepping for that is a good place to start.

**Comment by vollmerm** [comment]
I don't think there's a good reason any more to have primitive list operations built in. Ideally, we should be able to build a list data type directly in Gibbon and get the right asymptotic performance when using it.
