### ISSUE TITLE
Discussion: new type system with locations, regions, existentials

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#60]
This is related to the new compiler pipeline in #59.  I'll show it through a couple example programs:

```Haskell
id x = x
getRight v = case v of Node x y -> y
```

And then, after we infer location-enriched types for them, they have:

```Haskell
id       :: ∀r, a∊r. Tree_a -> Tree_a
getRight :: ∀r, a∊r. ∃ b∊r. b>a => Tree_a -> Tree_b
```
How do we get these types?  Pattern matching introduces existential locations for the fields, just like regular GADT pattern matching does.

**Comment by vollmerm** [comment]
We did design a new type system, but not with existentials. I think a new issue could be added for extending the language to potentially include existential types in order to express certain optimizations.
