### ISSUE TITLE
Plan for adding source locations / line numbers to the AST

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#68]
This is something that all decent compilers should do, but it's still not high priority.

However, the longer we delay, the larger the number of passes on the beta branch are which will need to be significantly refactored to admit source locations.

The current plan is that L1's Exp1 recursions will be replaced with `L Exp1` (using the type for located values from the `srcloc` package), hence ensuring that "every other node" in a walk down the AST is a source location node.

But parser support for this is not trivial.

 * Parsec has some support for extracting source positions, but it's not completely trivial to figure out how to use it.
 * S-Cargot (for S-expr parsing) uses Parsec internally, but does not seem to expose enough through it's regular exports to muck about and turn source locations on.

These complications are a reason to delay.

**Comment by ckoparkar** [comment]
Fixed by https://github.com/iu-parfunc/gibbon/commit/8f668c2a5482c5e909cd9b1a35da9593fe8bcb6e
