### ISSUE TITLE
Tree insert benchmark fails to compile

### ISSUE THREAD

**Issue by vollmerm** [iu-parfunc/gibbon#88]
Currently, running Gibbon on `test_litmus_search_tree_insert.gib` fails here:

```
 [compiler] Running pass, L3.typecheck
gibbon: Var "case350" not found. Checking: 
: VarE "case350"
CallStack (from HasCallStack):
  error, called at src/Packed/FirstOrder/L3/Typecheck.hs:341:21 in gibbon-0.1.0.0-9Cf0D9RlXe37x08aMLXLaN:Packed.FirstOrder.L3.Typecheck
```

It appears to fail the typechecker in L3 due to an unbound `case` variable. The unbound variable in this error, `case350`, was introduced in the `RepairProgram` pass, which produced the following line in the log:

```
Inside caserhs, for ("Node^",[(Var "sz239",Var "case347"),(Var "n17",Var "case348"),(Var "l8",Var "case349"),(Var "r9",Var "case350")],[CursorTy,IntTy,PackedTy "Tree" (Var "loc264"),PackedTy "Tree" (Var "loc265")])
```

The actual program source before this pass is far too large to include inline in this issue, but the full error log is uploaded here: https://gist.github.com/vollmerm/b2a0a22dd65832466871149dd33edcf6

**Comment by ckoparkar** [comment]
Fixed by 52ccdcd and c9603bd.
