### ISSUE TITLE
Implement Pretty Printing for IRs

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#90]
I noticed that there is not an open issue for this.  It's not a hurry, but it would be nice to eventually pretty-print in a syntax that is much more concise and closer to the source language.  For example, Accelerate pretty prints IRs in a compact Haskell-like syntax.

**Comment by ckoparkar** [comment]
[Gibbon.Pretty](https://github.com/iu-parfunc/gibbon/blob/master/gibbon-compiler/src/Gibbon/Pretty.hs).
