### ISSUE TITLE
Implement copy-prop late in the compiler

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/gibbon#91]
Heck, maybe not just late, maybe "early and often".

Our IRs are way harder to read when they're full of meaningless copy variables.  Along with pretty printing (#90), copy-prop would make the DEBUG logs way more manageable.  Likewise, the generated C code (or LLVM IR) would be easier to debug with a low-level runtime debugger.

**Comment by ckoparkar** [comment]
The main bit here is to implement copy propagation (as an L3->L3 pass) after `Cursorize` because it introduces a lot of this copy variable noise. Doing it early and often is a nice bonus!

**Comment by ckoparkar** [comment]
This has been implemented here: https://github.com/iu-parfunc/gibbon/blob/a48a09eb19c13c47ce47d93b525fc9f78c14dd8c/gibbon-compiler/src/Gibbon/Passes/Simplifier.hs#L212
